# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('facebook', models.TextField(blank=True, max_length=100)),
                ('twitter', models.TextField(blank=True, max_length=100)),
                ('github', models.TextField(blank=True, max_length=100)),
                ('linkedin', models.TextField(blank=True, max_length=100)),
                ('google', models.TextField(blank=True, max_length=100)),
                ('mentor', models.BooleanField()),
                ('interest_in_technology', models.BooleanField()),
                ('interest_in_marketing', models.BooleanField()),
                ('interest_in_legal', models.BooleanField()),
                ('interest_in_leadership', models.BooleanField()),
                ('interest_in_business', models.BooleanField()),
                ('interest_in_operations', models.BooleanField()),
                ('interest_in_investments', models.BooleanField()),
                ('interest_in_professional_development', models.BooleanField()),
                ('mentee', models.BooleanField()),
                ('learn_technology', models.BooleanField()),
                ('learn_marketing', models.BooleanField()),
                ('learn_legal', models.BooleanField()),
                ('learn_leadership', models.BooleanField()),
                ('learn_business', models.BooleanField()),
                ('learn_operations', models.BooleanField()),
                ('learn_investments', models.BooleanField()),
                ('learn_professional_development', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
