# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ranking',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
