# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0006_auto_20170404_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='facebook',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datos',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datos',
            name='mentee',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datos',
            name='mentor',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='datos',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
