# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0009_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='comments',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
