# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0010_auto_20170410_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('C', 'Canceled'), ('S', 'Scheduled'), ('D', 'Done'), ('I', 'In Process'), ('O', 'On Hold')], max_length=1),
        ),
    ]
