# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0012_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_mode',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Mentee', 'Mentee')], default='Mentee', max_length=6),
        ),
    ]
